[phases.setup]
nixPkgs = ["python310", "nodejs-18_x"]

[phases.install]
cmds = [
    "pip install -r backend/requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "uvicorn backend.server:app --host 0.0.0.0 --port $PORT"
