[phases.setup]
nixPkgs = ["python311Full", "nodejs_18"]

[phases.install]
cmds = [
  "cd frontend && NPM_CONFIG_PRODUCTION=false npm ci",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "uvicorn backend.server:app --host 0.0.0.0 --port $PORT"
